server:
  port: ${SERVER_PORT:8081}

app:
  satellite:
    url: ${SERVER_URL:http://localhost:8080}
    missions:
      - targetType: CONSTELLATION
        constellationName: "Зенит-3"
        cron: "*/10 * * * * *"


